<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<Title>$(AssemblyName)</Title>
	<Version>$(GlobalVersion)</Version>
	<Company>$(GlobalCompany)</Company>
	<Copyright>$(GlobalCopyright)</Copyright>
	<Authors>$(GlobalAuthors)</Authors>
	<Description>Core Package for Lunatic Panel's PLugin</Description>
	<PackageProjectUrl>https://github.com/mshimshon/LunaticPanel</PackageProjectUrl>
	<RepositoryUrl>https://github.com/mshimshon/LunaticPanel</RepositoryUrl>
	  <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="LunaticPanel.Core" PrivateAssets="false" />
	<PackageReference Include="LunaticPanel.Core.Abstraction" PrivateAssets="false" />
    <PackageReference Include="LunaticPanel.Core.Extensions" PrivateAssets="false" />
    <PackageReference Include="LunaticPanel.Core.Utils" />
    <PackageReference Include="LunaticPanel.Engine.Keys" PrivateAssets="false" />
    <PackageReference Include="Microsoft.AspNetCore.Components" />
	<PackageReference Include="Microsoft.Extensions.Logging" />
	<PackageReference Include="MudBlazor" PrivateAssets="false" />
	<PackageReference Include="Newtonsoft.Json" />
	<PackageReference Include="CoreMap" GeneratePathProperty="true" />
	<PackageReference Include="MediHater" GeneratePathProperty="true" />
	<PackageReference Include="StatePulse.Net" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GameHost.Core\GameHost.Core.csproj" />
    <ProjectReference Include="..\Kernel.Abstractions\Kernel.Abstractions.csproj" />
    <ProjectReference Include="..\Kernel\Kernel.csproj" />
  </ItemGroup>

  <ItemGroup>
	  <Folder Include="Features\LinuxGameServer\Application\Config\" />
	  <Folder Include="Features\LinuxGameServer\Application\Payloads\Requests\" />
	  <Folder Include="Features\LinuxGameServer\Application\Mediator\Notifications\Handlers\" />
	  <Folder Include="Features\LinuxGameServer\Web\Hooks\Events\" />
	  <Folder Include="Features\Mods\Application\Bash\" />
	  <Folder Include="Features\Mods\Application\Hooks\" />
	  <Folder Include="Features\Mods\Web\Hooks\Queries\" />
	  <Folder Include="Features\Mods\Web\Hooks\Events\Scheduled\" />
	  <Folder Include="Features\SystemInfo\Application\Mediator\Commands\" />
	  <Folder Include="Features\SystemInfo\Infrastructure\Exceptions\" />
	  <Folder Include="Features\SystemInfo\Web\Hooks\Queries\" />
	  <Folder Include="Web\Pages\Hooks\Events\" />
	  <Folder Include="Web\Pages\Hooks\Queries\" />
	  <Folder Include="wwwroot\" />
  </ItemGroup>

	<Target Name="RemoveHostOwnedAssembliesAfterBuild" AfterTargets="CopyFilesToOutputDirectory" >

		<ItemGroup>
			<_DeleteDlls Include="&#xD;&#xA;				$(OutputPath)**\Microsoft.*.dll;&#xD;&#xA;				$(OutputPath)**\LunaticPanel.*.dll;&#xD;&#xA;				$(OutputPath)**\LunaticPanel.*.*.dll;&#xD;&#xA;				$(OutputPath)MudBlazor.dll&#xD;&#xA;			" />
		</ItemGroup>

		<Delete Files="@(_DeleteDlls)" />
	</Target>
</Project>
