<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <GlobalVersion>0.1.0</GlobalVersion>
    <GlobalCompany>Maksim Shimshon</GlobalCompany>
    <GlobalAuthors>Maksim Shimshon</GlobalAuthors>
    <GlobalCopyright>Maksim Shimshon © 2026</GlobalCopyright>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="LunaticPanel.Core" Version="0.1.832" />
    <PackageVersion Include="LunaticPanel.Core.Abstraction" Version="0.1.832" />
    <PackageVersion Include="LunaticPanel.Core.Extensions" Version="0.1.832" />
    <PackageVersion Include="LunaticPanel.Core.Utils" Version="0.1.832" />
    <PackageVersion Include="LunaticPanel.Core.Utils.Abstraction" Version="0.1.832" />
    <PackageVersion Include="LunaticPanel.Engine.Keys" Version="0.1.832" />
    <PackageVersion Include="Microsoft.AspNetCore.Components" Version="10.0.7" />
    <PackageVersion Include="Microsoft.Extensions.FileProviders.Physical" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.7" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.1" />
    <PackageVersion Include="MudBlazor" Version="9.4.0" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageVersion Include="StatePulse.Net" Version="2.9.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.Web" Version="10.0.3" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.7" />
    <PackageVersion Include="MediHater" Version="1.0.0" />
    <PackageVersion Include="CoreMap" Version="1.1.2" />
    <PackageVersion Include="StatePulse.Net.Abstractions" Version="2.9.0" />
    <PackageVersion Include="WolverineFx" Version="5.38.0" />
  </ItemGroup>
</Project>