services:
  - import_from: "../../LunaticPanel/src/lpcli-compose.yml"  # import all lunatic panel services.

plugins:
  - import_from: "../../LunaticPanel/src/Plugins/lpcli-compose.yml"  # Import all official panel shipped plugins  
  - dotnet_project: "./GameHost/GameHost.csproj"
    enabled: true
  - snap: "gamehost_init_done"
post_processing:
  
  - command: "if ! id -u lgsm >/dev/null 2>&1; then useradd -m -d /home/lgsm -s /usr/sbin/nologin lgsm; fi" # PreCreate LGSM Username 
  - import_from: "../../LunaticPanel/src/lpcli-compose.yml"  # Import Lunatic Panel PP
  - import_from: "../../GameHost.Games/lpcli-compose.yml"  # Import Setup Game Server Libs

